chore: update weekly logic

diff --git a/.github/workflows/weekly_ci.yaml b/.github/workflows/weekly_ci.yaml
--- a/.github/workflows/weekly_ci.yaml
+++ b/.github/workflows/weekly_ci.yaml
@@ -35,5 +35,16 @@ jobs:
     - name: Clone repository
       run: |
         git clone https://github.com/hypernetwork-research-group/hypertorch.git
-        cd hypertorch
-        uv run scripts/run_examples.sh
+
+        mv hypertorch/examples examples
+
+        mv hypertorch/scripts/run_examples.sh .
+        chmod +x run_examples.sh
+
+        ./run_examples.sh 2>&1 | tee run_examples_out.txt
+
+        if grep -q "^The following examples failed:" run_examples_out.txt; then
+          echo "===== Example failures detected ====="
+          sed -n '/^The following examples failed:/,$p' run_examples_out.txt
+          exit 1
+        fi
