fix: fix windows ci

diff --git a/.github/workflows/weekly_ci.yaml b/.github/workflows/weekly_ci.yaml
--- a/.github/workflows/weekly_ci.yaml
+++ b/.github/workflows/weekly_ci.yaml
@@ -116,14 +116,10 @@ jobs:
           uv pip install "torch>=2.12,<3.0" --index-url https://download.pytorch.org/whl/cpu
           uv pip install pyg-lib --find-links https://data.pyg.org/whl/torch-2.12.0+cpu.html
           uv pip install hypertorch
+          uv run bash ./scripts/run_examples.sh 2>&1 | tee run_examples_out.txt
 
-    - name: Run examples
-      shell: bash
-      run: |
-        uv run --python test-env bash ./scripts/run_examples.sh 2>&1 | tee run_examples_out.txt
-
-        if grep -q "^The following examples failed:" run_examples_out.txt; then
-          echo "===== Example failures detected ====="
-          sed -n '/^The following examples failed:/,$p' run_examples_out.txt
-          exit 1
-        fi
+          if grep -q "^The following examples failed:" run_examples_out.txt; then
+            echo "===== Example failures detected ====="
+            sed -n '/^The following examples failed:/,$p' run_examples_out.txt
+            exit 1
+          fi
